### ISSUE TITLE
bigWig file names

### ISSUE THREAD

**Issue by DoaneAS** [daler/trackhub#34]
Hi,  

Thanks a lot for this package, it's super helpful.  

Just a quick note that file names for bigWig files with the extension `.bw` are being changed to `.bigWig` when calling `trackhub.upload.upload_hub(...)`.  I'm not sure if this is done on purpose, but you may want to put it in the change log, or allow `.bw` files (which are common).  

thanks again

**Comment by daler** [comment]
This is intentional -- if no `filename` is specified, by default it will build a symlink name out of `{trackname}.{tracktype}`. You can get more control over the symlink name by using the `filename` argument. More info at https://daler.github.io/trackhub/changelog.html#local-fn-argument-is-now-replaced-by-source, but it could certainly be better documented.

**Comment by daler** [comment]
(Thank you for reporting this though!)

**Comment by DoaneAS** [comment]
thanks, I just discovered that it builds the `{trackname}.{tracktype}` name, and came to edit my post.  In any case, this is quite useful now that I understand what is happening.  thank you
